---
lang: ru
format:
  docx:
    reference-doc: reference.docx
    number-sections: false
    toc: false
    toc-depth: 2
editor: visual
bibliography: bibliography.bib
csl: gost-r-7-0-5.csl
---

# Клеточная конкуренция как механизм контроля качества в молодом эмбриональном развитии млекопитающих

# **ГЛАВА 1. АНАЛИТИЧЕСКИЙ ОБЗОР**

## **1.1. Клеточная конкуренция: основные понятия**

Многоклеточные организмы характеризуются сложными межклеточными взаимодействиями, одним из которых является клеточная конкуренция. Клеточная конкуренция представляет собой процесс, в ходе которого определённые жизнеспособные клетки вытесняются из ткани из-за генетических или функциональных отличий. Этот механизм был впервые описан в экспериментах с Drosophila melanogaster, имеющих мозаичный кариотип, где клетки с мутациями в генах рибосомных белков (Rp) подвергались апоптозу в присутствии клеток дикого типа [@morata_minutes_1975]. Несмотря на жизнеспособность элиминированных клеток, в мозаичном организме они уступают место более приспособленным клеткам дикого типа.

Клеточная конкуренция представляет собой активный биологический процесс, который уничтожает клетки только в том случае, если они отличаются от соседних клеток либо генетически, либо по уровню экспрессии генов. Этот механизм принципиально отличается от пассивной клональной экспансии, которая происходит естественным путем вследствие различной интенсивности роста и пролиферации отдельных клеточных популяций. Активный характер клеточной конкуренции получил убедительное подтверждение с открытием "суперконкурентов" – генотипов клеточных популяций, способных селективно уничтожать близлежащие клетки дикого типа. Примером служат клетки имагинального диска дрозофилы (Drosophila melanogaster) с повышенной экспрессией гена Myc (гомолог которого у млекопитающих является онкогеном). Независимо от механизма усиления экспрессии - будь то дополнительная копия геномного локуса или трансген, вызывающий выраженную экспрессию с промотора тубулина, - такие клетки демонстрируют способность элиминировать клетки дикого типа [@cova_drosophila_2004; @cova_drosophila_2004]. Принципиально важно отметить, что гибель клеток дикого типа не является следствием их врожденных генетических дефектов. Напротив, это результат активного селективного процесса, инициируемого клетками с измененным генотипом.

Аналогичные механизмы клеточной конкуренции были обнаружены и у млекопитающих. Убедительным доказательством служат исследования, в которых умеренная сверхэкспрессия мышиного онкогена Myc, под контролем промотора Rosa26, создает суперконкурентные клетки, которые демонстрируют способность элиминировать контрольные клетки в эмбриональном эпибласте [@claveria_myc-driven_2013]. Принципиально важно, что в отсутствие суперконкурентов контрольные клетки развиваются без видимых отклонений. Более того, исследователи установили, что подавление элиминации клеток дикого типа становится возможным при экспрессии антиапоптотического белка p35, что указывает на наличие специфического механизма межклеточного взаимодействия, отличного от случайных процессов клеточной гибели [@claveria_myc-driven_2013].

Клеточная конкуренция выполняет функцию естественного фильтра, который обеспечивает формирование здоровой и генетически однородной клеточной популяции. Этот механизм можно рассматривать как своеобразный молекулярный контроль качества, который предотвращает накопление в тканях менее приспособленных клеток.

## 1.2. Разнообразие процессов клеточной конкуренции

### 1.2.1. Клеточная конкуренция в печени

Первые работы по изучению клеточной конкуренции у млекопитающих были сосредоточены на процессах репопуляции печеночной ткани [@oertel_cell_2006; @ding_spontaneous_2011]. Ранние научные исследования выявили уникальные механизмы межклеточного взаимодействия, происходящие при замещении гепатоцитов.

Частичная гепатэктомия создает условия для активной пролиферации фетальных стволовых и прогениторных клеток, введенных в печень крысы. При этом происходит замещение ткани хозяина донорскими клетками, сопровождающееся апоптозом окружающих гепатоцитов. Этот процесс носит целенаправленный характер и не происходит без введения трансплантированных клеток [@oertel_cell_2006].

Конкуренция клеток также наблюдалась при трансплантации донорских гепатоцитов дикого типа мышам, экспрессирующим мутантный ген человеческого α1-антитрипсина [@ding_spontaneous_2011]. Трансплантированные гепатоциты дикого типа проявляли конкурентное преимущество, усиливая апоптоз мутантных гепатоцитов хозяина. При этом общий размер печени оставался неизменным, что указывает на селективную замену клеток [@ding_spontaneous_2011].

### 1.2.2. Клеточная конкуренция в иммунной системе

Конкуренция клеток в иммунной системе играет важную роль в поддержании гомеостаза. Одним из примеров такой конкуренции является взаимодействие клеток, находящихся в состоянии стресса, с клетками, не подвергшимися стрессовым воздействиям [@bondar_p53-mediated_2010; @marusyk_irradiation_2010].

Небольшая доза облучения гемопоэтических стволовых клеток (ГСК) позволяет создать уникальную экспериментальную модель для изучения клеточной конкуренции, в то время как большая доза облучения приводит к полному уничтожению клеток, что неизбежно вызывает иммунодефицит. При мягком облучении ГСК выживают и сохраняют способность поддерживать иммунную функцию, но подвергаются стрессу и оказываются в невыгодном положении, когда вступают в конкурентные отношения с необлученными клетками или с клетками, имеющими дефицит экспрессии гена-супрессора опухолей Tp53 [@bondar_p53-mediated_2010; @marusyk_irradiation_2010].

Канцерогенное действие радиации может быть результатом конкуренции между клетками с различной активностью p53. Такая конкуренция способствует селективному преимуществу клеточных линий, экспрессирующих мутантный Tp53 [@bondar_p53-mediated_2010; @marusyk_irradiation_2010]. Важно отметить, что клеточная конкуренция возникает после ответа на повреждение ДНК, вызванного радиацией, и преимущественно затрагивает гемопоэтические стволовые клетки, а не лимфоциты [@bondar_p53-mediated_2010].

В рамках исследования, посвященного p53-опосредованной конкуренции гемопоэтических стволовых и прогениторных клеток, было установлено, что p16-зависимая сенесценция стволовых клеток происходит только в присутствии конкурирующих стволовых клеток с более низким уровнем активности p53 [@bondar_p53-mediated_2010]. Клеточная конкуренция такого типа может потенциально способствовать клональной экспансии зарождающихся раковых клеток.

Некоторые исследования выдвинули гипотезу о существовании клеточной конкуренции между резидентными и новыми предшественниками Т-лимфоцитов в тимусе. Этот процесс, вероятно, играет важную роль в снижении риска лейкозогенеза из резидентных клеток [@martins_cell_2014; @paiva_thymus_2018].

### 1.2.3. Клеточная конкуренция в культурах тканей

Явления клеточной конкуренции были исследованы в экспериментальных условиях культивирования тканей, в частности, с использованием клеточной линии эпителиальных клеток почки собаки Мадина-Дарби (MDCK). В ходе экспериментов было установлено, что клетки, экспрессирующие онкогенный вариант RAS (RAS-V12), связанный с повышенной клеточной пролиферацией и выживаемостью, сохраняют способность к росту в эпителиальном слое. Однако, если экспрессию RAS-V12 индуцировать в отдельных клетках внутри эпителиального слоя MDCK в культуре, такие клетки часто теряются из слоя из-за их вытеснения (экструзии) [@hogan_characterization_2009].

Аналогичные наблюдения были сделаны для клеток MDCK, экспрессирующих v- SRC, ERBB2 или конститутивно активный YAP, а также для клеток MDCK, в которых был нокаутирован ген-супрессор опухоли SCRIB (кодирующий детерминанту клеточной полярности Scribble) или MAHJ37 (кодирующий E3 убиквитин-лигазу Mahjong, также известную как VPRBP или DCAF1) [@kajita_interaction_2010; @leung_outgrowth_2012; @chiba_mdck_2016; @norman_loss_2012; @tamori_involvement_2010]. Таким образом, на начальной стадии канцерогенеза нормальные эпителиальные клетки способны распознавать потенциально отличающиеся одиночные клетки и активно удалять их из эпителиальных тканей. Это означает, что нормальный эпителий обладает противоопухолевой активностью, не затрагивающей иммунные клетки, которая называется защита эпителия от рака (EDAC, epithelial defense against cancer) [@yamauchi_epithelial_2012].

### 1.2.4. Клеточная конкуренция в эмбриогенезе мыши

Активность белка p53 существенно влияет на конкуренцию клеток в эмбриональном развитии мыши. В ходе исследований выяснилось, что нокдаун генов Tp53 и топоизомеразы 1 позволяет клеткам вытеснять эмбриональные стволовые клетки дикого типа при совместном введении в бластоцисты. Таким образом, в ходе эмбрионального развития мыши подавление экспрессии Тp53, по-видимому, благоприятствует клеткам, находящимся на ранней стадии дифференцировки [@dejosez_safeguards_2013].

Изменения активности p53 могут опосредованно влиять на клеточные взаимодействия в мозаичных организмах. Например, в химерных эмбрионах мыши тетраплоидные (4n) клетки элиминируются из эмбриональных тканей после гаструляции, хотя сохраняются в экстраэмбриональных тканях [@tarkowski_development_1977; @nagy_embryonic_1990]. Этот процесс напрямую зависит от уровня p53 [@horii_p53_2015]. Повышенный уровень белка в 4n клетках приводят к их апоптозу при взаимодействии с диплоидными (2n) клетками [@sancho_competitive_2013].

Аналогичные механизмы клеточной конкуренции наблюдаются и при других генетических мутациях. Клетки с мутантным геном Bmpr1a элиминируются в результате конкуренции с немутантными клетками, что также опосредовано активностью p53 [@bowling_p53_2018]. Мутации в семействе убиквитин-лигаз MDM2, подавляющем транскрипционную активность p53, также приводят к элиминации клеток в процессе эмбриогенеза [@zhang_p53_2017].

На шестой день эмбрионального развития мыши (E6) наблюдается массовый апоптоз клеток эпибласта, который интерпретируется как конкуренция между клетками с разным уровнем экспрессии Myc [@claveria_myc-driven_2013]. Поскольку Myc способствует сохранению плюрипотентности, устранение клеток с низким уровнем Myc предотвращает преждевременную дифференцировку и поддерживает плюрипотентное состояние популяции клеток [@diaz-diaz_pluripotency_2017].

Некоторые исследования обнаружили клеточную конкуренцию даже на более ранних стадиях – в предимплантационном эпибласте. Клетки с низкой активностью транскрипционного фактора TEAD1 и его кофактора YAP элиминируются, что способствует поддержанию плюрипотентности [@hashimoto_epiblast_2019].

Механизмы клеточной конкуренции продолжают действовать и в более позднем эмбриональном периоде. В эпидермисе мыши клетки с пониженной экспрессией Mycn элиминируются различными механизмами между 12.5 и 17.5 днями развития. Предполагается, что такая конкуренция необходима для формирования оптимальной эпителиальной барьерной функции [@ellis_distinct_2019].

Клеточная конкуренция не ограничивается только эмбриональным периодом развития организма, но продолжается и на постэмбриональных стадиях. Помимо ранее описанных механизмов конкурентного взаимодействия в печени и иммунной системе, яркий пример постэмбриональной клеточной конкуренции можно наблюдать в сердце. В сердечной ткани происходит процесс, при котором кардиомиоциты с повышенной экспрессией онкогена Myc способны постепенно замещать обычные клетки, при этом орган продолжает нормально функционировать [@villadelcampo_cell_2014].

## 1.3. Физиологическая значимость клеточной конкуренции

Одной из общих черт многих описанных выше примеров клеточной конкуренции является их экспериментальная природа. То есть такие процессы возникают в результате искусственно вызванной генетической мозаичности (исключением является эндогенная конкуренция в эпибласте мышей) [@claveria_myc-driven_2013; @diaz-diaz_pluripotency_2017]. Этот факт вызывал у некоторых ученых сомнения в физиологической значимости клеточной конкуренции.

Важно отметить, что спонтанное возникновение генетической мозаичности в организме действительно распространено и возникает как следствие хромосомных аномалий, обусловленных ошибками митоза, а также соматических мутаций. Большинство эмбрионов содержат некоторое количество анеуплоидных клеток на раннем этапе развития [@van_echten-arends_chromosomal_2011; @mccoy_mosaicism_2017]. Этот факт может показаться удивительным, учитывая, что анеуплоидия является основной причиной выкидышей и врожденных дефектов. Однако анеуплоидные клетки обычно устраняются из мозаичных эмбрионов до рождения [@zamani_esteki_vitro_2019].

Моделирование элиминации анеуплоидных клеток было проведено на мышах путем временного ингибирования контрольной точки сборки веретена деления, что приводило к образованию анеуплоидных бластомеров. При введении таких клеток в эмбрионы наблюдалось, что анеуплоидные клетки, как правило, элиминировались еще до имплантации. Более того, эмбрионы, в которых до 50% клеток изначально были анеуплоидными, часто рождались как жизнеспособные мыши без явных признаков аномальных клеток [@bolton_mouse_2016]. Анеуплоидные клетки также могут устраняться из эмбрионов на более поздних этапах развития. Например, в коре головного мозга мышей на 13,5-й день эмбрионального развития (E13.5) около 30% клеток являются анеуплоидными, но через 6 месяцев после рождения их доля снижается до \~1% [@andriani_whole_2016].

Соматические мутации также являются эндогенной причиной возникновения мозаицизма. С возрастом количество соматических мутаций существенно накапливается, что может приводить к клональной селекции и изменениям в популяциях клеток, что напоминает клеточную конкуренцию [@martincorena_somatic_2015]. Наиболее ярко клональный отбор проявляется в иммунной системе, где с возрастом может доминировать одна гемопоэтическая линия клеток. Важно отметить, что доминирующая популяция клеток часто содержит мутации, характерные для лейкемий и лимфом, но при этом поддерживает нормальное функционирование крови и не вызывает злокачественной трансформации [@steensma_clonal_2015]. Аналогичным образом, нормальная кожа человека и эпителий пищевода часто содержат линии мутантных клеток, что выявлено с помощью методов глубокого секвенирования [@martincorena_high_2015; @martincorena_somatic_2018]. Например, в эпителии пищевода, мутации в гене NOTCH1, кодирующем рецепторный белок и ранее считавшемся онкогенным, чаще встречаются в нормальной ткани, чем в опухолях [@martincorena_somatic_2018]. Это говорит о том, что такие мутации, скорее, предшествуют трансформации, чем способствуют ей.

Распространенность генетического мозаицизма в процессах эмбриогенеза и старения означает, что клеточная конкуренция может возникать не только в результате экспериментальных манипуляций, но и как следствие ошибок при делении клетки и соматических мутаций.

Конкуренция клеток играет важную роль в контроле качества, поддержании гомеостаза тканей, в нормальном развитии эмбриона, а также может функционировать как механизм подавления или стимулирования онкогенеза.

## 1.4. Молекулярные механизмы клеточной конкуренции

Особый научный интерес к молекулярным механизмам взаимодействия конкурирующих клеток обусловлен их потенциальной связью с онкогенезом, поскольку изменения в экспрессии протоонкогенов и генов-супрессоров опухолей часто лежат в основе клеточной конкуренции.

Исследователи выделяют три общих механизма, через которые различия между клетками могут вызывать клеточную конкуренцию:

1.  Различия между клетками могут быть выявлены через специфическое молекулярное распознавание, что приводит к локальной активации процесса клеточной конкуренции.
2.  Различия между клетками могут нарушить баланс сигналов, управляющих клеточной гибелью и выживанием. Это создает неблагоприятную среду для одной из популяций клеток и запускает клеточную конкуренцию, даже без необходимости специфического молекулярного распознавания.
3.  Различия в скорости роста клеточных популяций могут создавать клеточный стресс из-за механического воздействия, который влияет на выживаемость, пролиферацию и подвижность клеток, что также может инициировать процесс клеточной конкуренции [@shraiman_mechanical_2005; @matamoro-vidal_multiple_2019].

### 1.4.1. Молекулярное распознавание конкурирующих клеток

В организме Drosophila melanogaster ген SCRIB кодирует PDZ-белок, который участвует в формировании апико-базальной полярности эпителиальных клеток. Мутация или подавление экспрессии SCRIB приводит к чрезмерному росту эпителия на имагинальных дисках, формируя дезорганизованные клеточные массы. Однако, клетки с мутацией SCRIB, находящиеся среди диких клеток, элиминируются [@brumby_scribble_2003; @bilder_cooperative_2000]. Из-за способности общих мутаций SCRIB вызывать неоплазию, клеточная конкуренция, удаляющая клетки с мутациями SCRIB или другими мутациями в генах, связанных с эпителиальной полярностью, рассматривается как механизм, подавляющий опухолевый рост. Генетические исследования, направленные на изучение основ такой конкуренции, выявили специфические сигнальные события, происходящие на границе между мутантными клетками и клетками дикого типа.

У клеток с мутацией SCRIB, находящихся на границе с дикими клетками, тирозинфосфатаза Ptp10D перемещается с апикальной на базолатеральную поверхность мембраны, где она взаимодействует со своим трансмембранным лигандом — белком Stranded at second (Sas) [@yamamoto_ligand_2017]. Это перемещение, вероятно, связано с нарушением клеточной полярности, поскольку оно также наблюдается при конкуренции клеток с дефектами в других генах полярности [@yamamoto_ligand_2017]. Сигналы, зависимые от Ptp10D, подавляют активность Ras в SCRIB-мутантных клетках, контактирующих с дикими клетками. Это подавление снижает сигнал, который в противном случае противодействовал бы повышенной активности Jnk c-Jun N-terminal kinases), вызванной сигналами от Egr, гомолога фактора некроза опухоли (TNF) у млекопитающих [@yamamoto_ligand_2017].

Вдали от границы с дикими клетками совместная активность Jnk и Ras стимулирует пролиферацию и неоплазию SCRIB-мутантных клеток. Однако на границе, где активность Ras подавлена, Jnk способствует базальной экструзии SCRIB -мутантных клеток. Процесс экструзии связан с подавлением уровня E-cadherin через аутокринные сигналы Slit–Robo и активацию белка Enabled (Ena) [@vaughen_slit-robo_2016]. Клетки дикого типа также способствуют удалению мутантных клеток, поглощая их. Этот процесс вызван повышенной экспрессией рецептора, гомологичного рецептору тромбоцитарного фактора роста (Pvr), в окружающих диких клетках [@ohsawa_elimination_2011].

Таким образом, данная форма клеточной конкуренции, подавляющая опухолевый рост, зависит от прямых молекулярных взаимодействий Ptp10D и Sas, которое происходит исключительно между конкурирующими популяциями клеток [@yamamoto_ligand_2017; @vaughen_slit-robo_2016; @ohsawa_elimination_2011].

### 1.4.2. Механизм элиминации без молекулярного распознавания

Уничтожение клеток дикого типа клетками-суперконкурентами с повышенной экспрессией Myc зависит от генов, связанных с врожденным иммунным ответом, включая один или несколько Toll-подобных рецепторов (TLRs) и транскрипционные факторы семейства NF-κB [@meyer_ancient_2014]. У клеток имагинальных дисков D. melanogaster, сверхэкспрессирующих Myc, уровень сериновых протеаз modSP и spaetzle-processing enzyme (SPE) выше, чем у клеток дикого типа [@alpar_spatially_2018]. Эти ферменты локально расщепляют большее количество секретируемого белка Spaetzle (Spz) до его активной формы [@alpar_spatially_2018]. Активный Spz негативно влияет на выживаемость соседних клеток дикого типа, связываясь с их TLR и вызывая активацию сигнального пути NF-κB, что приводит к апоптозу [@alpar_spatially_2018]. Интересно, что клетки с повышенной экспрессией Myc экспрессируют TLR, такие как Toll-2, Toll-8 и Toll-9 в меньшем количестве [@alpar_spatially_2018].

Согласно рабочей модели суперконкуренции, клетки дикого типа, находящиеся рядом с клетками с высокой экспрессией Myc, подвергаются токсическому воздействию сигнального пути NF-κB из-за того, что только они экспрессируют нормальные уровни TLR-рецепторов в условиях повышенной активности Spz [@alpar_spatially_2018]. Данный пример показывает, как клетки дикого типа могут быть подвергнуты элиминации рядом с клетками, экспрессирующими высокий уровень Myc, без необходимости молекулярного распознавания клеток дикого типа суперконкурентными клетками.

### 1.4.3. Механизм элиминации при механическом воздействии на клетки

Клеточная конкуренция часто возникает между клетками с различными темпами роста, так как это различие может приводить к клеточному стрессу, особенно в ткани эпителия, где перестройка клеток ограничена соединениями адгезии [@cova_drosophila_2004; @shraiman_mechanical_2005; @simpson_differential_1981].

Например, гиперпластические клетки, окруженные в эпителии клетками с менее активным пролиферативным потенциалом, будут подвергаться сжатию и оказывать реактивное давление на окружающие клетки [@mao_differential_2013]. Поскольку давление может способствовать элиминации клеток из эпителия, суперконкуренция гиперпластических клеток может быть обоснована апоптозом окружающих клеток, вызванным сжатием. При этом не происходит какого-либо другого молекулярного взаимодействия между клетками, особенно если менее пролиферирующие клетки обладают повышенной чувствительностью к сжатию, что приводит к их элиминации [@marinari_live-cell_2012; @eisenhoffer_crowding_2012; @levayer_tissue_2016].

Сжатие клеток дикого типа, расположенных вокруг гиперпластической линии клеток, может сопровождаться их растяжением в перпендикулярном направлении, что создаёт дополнительные различия между ними [@matamoro-vidal_multiple_2019]. Важно отметить, что границы между конкурирующими клетками, такими как Rp+/+ и Rp+/–, или между клетками дикого типа и клетками с генотипом-суперконкурентом Myc, становятся неровными [@aegerter-wilmsen_exploring_2010; @simpson_parameters_1979; @li_oriented_2009; @levayer_cell_2015; @li_engulfment_2007; @gudipaty_mechanical_2017]. Чем более неровной становится граница, тем больше клеток подвергаются воздействию другой популяции, что может объяснить повышение скорости апоптоза в клетках Rp+/–, когда они окружены клетками дикого типа [@matamoro-vidal_multiple_2019; @li_engulfment_2007]. Напротив, при ровных границах давление распределено равномернее, поэтому снижается интенсивность клеточной конкуренции.

Для полного понимания вклада механического стресса в клеточную конкуренцию требуется больше данных о том, как давление распределяется в тканях и какие сигнальные пути на него реагируют. Например, в эпителии Danio rerio, для элиминации клеток в ответ на сжатие ткани, необходим активируемый растяжением канал Piezo [@eisenhoffer_crowding_2012]. Однако, Piezo также необходим для пролиферации, активируемой растяжением, поэтому факторы, отличающие сжатие клеток от их растяжения, остаются неизученными [@gudipaty_mechanical_2017].

Особый интерес представляет изучение того, как механический стресс может влиять на клеточную конкуренцию в неэпителиальных тканях. В одном из исследований на клетках млекопитающих было показано, что при отдельном культивировании клетки с пониженной экспрессией SCRIB были более плоскими и прилегали менее плотно друг к другу, чем клетки дикого типа[@wagstaff_mechanical_2016]. Однако при совместном культивировании клетки, обедненные белком SCRIB, становились сжатыми и вертикально вытянутыми. Важно отметить, что сжатие было достаточным, чтобы вызвать апоптоз клеток с пониженной экспрессией SCRIB даже в отсутствие нормальных клеток [@wagstaff_mechanical_2016].

В клетках, с подавленной экспрессией SCRIB, в результате вызываемой сжатием активности Rho-ассоциированной протеинкиназы (ROCK), зависящей от p38-киназы, повышался уровень р53. Одной только умеренной активации р53 было достаточно, чтобы вызвать конкуренцию с клетками MDCK дикого типа. Это позволяет предположить, что p53 является основным регулятором клеточных процессов в данной экспериментальной системе [@wagstaff_mechanical_2016].

## **1.5. Конкуренция клеток на ранних стадиях развития млекопитающих**

Эмбрион млекопитающих демонстрирует уникальную пластичность, которая позволяет ему корректировать наличие аберрантных клеток, регулировать рост в соответствии со стадией развития и даже интегрировать клетки другого вида для формирования полностью функциональных органов. Одним из ключевых механизмов, обеспечивающих такую пластичность, является клеточная конкуренция.

Клеточная пластичность в эмбриогенезе проявляется в продолжительном периоде сохранения клетками широкого потенциала развития, сначала в тотипотентном, а затем и в плюрипотентном состоянии. В эмбриогенезе мыши некоторые клетки эмбриона остаются плюрипотентными до 8 дня гестации, а у человека плюрипотентные клетки можно обнаружить в 16-19-дневных эмбрионах [@tyser_single-cell_2021; @osorno_developmental_2012]. Принципиально важно отметить, что даже после инициации дифференцировки потенциально клетки некоторое время сохраняют способность изменять траекторию своего развития если окажутся в неправильной среде или после элиминации клеток другой линии [@plusa_distinct_2008; @guo_human_2021]. Но, несмотря на этот потенциал, некоторые клетки все же совершают ошибки в процессе дифференцировки. В таких случаях другая форма пластичности помогает эмбриону приспособиться к этим ошибкам, проявляясь на тканевом уровне в виде удаления аберрантных клеток и активации механизмов компенсаторного роста [@diaz-diaz_pluripotency_2017; @hashimoto_epiblast_2019; @lima_cell_2021]. Аналогичным образом, когда клетки на ранних стадиях развития совершают митотические ошибки, приводящие к кариотипическим аномалиям, эмбрион способен к самокоррекции этих ошибок, устраняя аберрантные клетки и корректируя процессы деления клеток, чтобы компенсировать их потерю [@bolton_mouse_2016].

В значительной мере природа такой пластичности проявляется, когда размер эмбриона в предимплантационный период уменьшается или увеличивается вдвое с помощью экспериментальных манипуляций. В обоих случаях эмбрион адаптирует свой рост таким образом, что к ранней постимплантационной стадии его размер становится сопоставимым с размером немодифицированных эмбрионов [@lewis_mechanism_1982].

Элиминация аберрантных клеток и эксперименты с размером эмбриона убедительно демонстрируют существование одного или нескольких механизмов, посредством которых клетки могут оценивать собственные темпы пролиферации и статус приспособленности относительно соседних клеток, после чего действовать на основе этой информации для регуляции роста и приспособленности тканей. Исследования последних лет показывают, что клеточная конкуренция является одним из таких механизмов.

В контексте изучения клеточной конкуренции в раннем эмбриогенезе млекопитающих особый научный интерес представляет анализ элиминируемых клеточных популяций. Исследователи выделяют три основные группы клеток, подвергающихся удалению в процессе эмбрионального развития:

1.  Клетки с нарушенным статусом дифференцировки
2.  Клетки с кариотипическими аномалиями
3.  Клетки с митохондриальной дисфункцией

### **1.5.1. Элиминация клеток, отличающихся по стадии дифференцировки**

В процессе предимплантационного развития эмбриона млекопитающих формируются три основных линии клеток: эпибласт, который даст начало всем типам клеток организма; трофобласт, из которого формируется плацента; и гипобласт (первичная энтодерма), из которого развивается желточный мешок. Формирование трофобласта напрямую зависит от пространственного расположения клеток в эмбрионе. Наружные клетки морулы становятся трофэктодермой под влиянием комбинации позиционных, транскрипционных и механических сигналов, а оставшиеся клетки формируют внутреннюю клеточную массу (ВКМ) [@chan_integration_2020; @chazaud_lineage_2016]. Сигналы фактора роста фибробластов (FGF), исходящие от ВКМ, играют важную роль в регуляции трофэктодермы, хотя апоптоз в этой ткани практически не наблюдается [@nichols_suppression_2009]. Это позволяет предположить, что клетки, не предназначенные для формирования эмбриона, не подвергаются тщательной проверке их жизнеспособности.

Процесс дифференцировки ВКМ на клетки эпибласта или первичной энтодермы — одно из событий в развитии эмбриона мыши, где происходит клеточная конкуренция. Когда эмбрион состоит примерно из 32 клеток, внутренние клетки начинают приобретать транскрипционную идентичность либо эпибласта, либо первичной энтодермы, независимо от расположения внутри ВКМ [@chazaud_lineage_2016]. В этом процессе важную роль вновь играет сигнальный путь FGF, при этом клетки с наибольшим уровнем FGF4 образуют первичную энтодерму [@saiz_asynchronous_2016; @yamanaka_fgf_2010]. Эти клетки затем отделяются от эпибласта и выстраиваются вдоль полости, находящейся между ВКМ и трофэктодермой. Несмотря на то, что некоторые клетки ВКМ сохраняют способность менять направление развития даже после дифференцировки, появляется все больше доказательств того, что клетки, не прошедшие сортировку должным образом, элиминируются через механизм клеточной конкуренции [@grabarek_differential_2012].

Внутри ВКМ клеточная гибель наблюдается в процессе развития бластоцисты [@copp_interaction_1978]. Это связано с неправильным расположением клеток перед дифференцировкой в клетки эпибласта или первичной энтодермы [@plusa_distinct_2008]. Важно отметить, что эти неправильно расположенные клетки демонстрируют цитоплазматическую экспрессию YAP и низкую активность TEAD, что является маркером активации пути Hippo - известного регулятора клеточной конкуренции у дрозофилы [@hashimoto_epiblast_2019; @neto-silva_evidence_2010; @tyler_genes_2007; @ziosi_dmyc_2010]. Также исследователи заметили, что Tead1 или Yap1-мутантные эмбриональные стволовые клетки (ЭСК) демонстрируют низкую экспрессию факторов плюрипотентности, низкую экспрессию MYC и устраняются в химерах клетками дикого типа, что указывает на то, что низкой активности TEAD достаточно, чтобы вызвать конкуренцию клеток. Таким образом, у эмбриона в период, когда происходит дифференцировка клеток на клетки эпибласта и примитивной эндодермы, те клетки, которые остаются недифференцированны, активируют путь Hippo, что приводит к их уничтожению в результате конкуренции клеток. Однако, каким образом недифференцированные клетки идентифицируются как клетки, подлежащие устранению, и что приводит к цитоплазматической экспрессии YAP в этих клетках, неизвестно.

Появление технологий работы с эмбриональными стволовыми клетками и их использование для внесения генетических изменений у мышей предоставило исследователям возможность искусственно манипулировать числом клеток внутри ВКМ. В одном из первых исследований была раскрыта еще одна роль клеточной элиминации во время развития бластоцисты [@wang_at_2004]. При введении смеси идентифицируемых клональных линий ЭСК и анализе полученных химер постнатально было установлено, что из 5–15 линий донорских ЭСК только 1–3 линии подвергались клональной экспансии, что свидетельствует о сильной селекции клеток в процессе развития [@wang_at_2004]. Эти результаты послужили основой для новых исследований, которые использовали усовершенствованную методику культивирования ЭСК в среде «2i» с ингибированием MEK и GSK3 сигнальных путей.

В среде 2i с добавлением LIF (лейкемия-ингибирующего фактора) ЭСК поддерживаются в наивном состоянии плюрипотентности более гомогенно и их состояние ближе к состоянию клеток ВКМ на предимплантационной стадии развития эмбриона [@ying_ground_2008]. Напротив, клетки, культивируемые в стандартной сывороточной среде с LIF, демонстрируют гетерогенную экспрессию генов плюрипотентности, причем часть клеток находится в состоянии, близком к дифференцировке, их транскрипционный профиль соответствует клеткам эпибласта на ранней постимплантационной стадии развития эмбриона [@boroviak_ability_2014; @kolodziejczyk_single_2015]. Сравнительный анализ поведения клеток, культивируемых в этих двух условиях, с использованием метода визуализации живых клеток, показал, что в сывороточной среде с LIF значительно больше клеток подвергается гибели [@alexandrova_selection_2015]. Эти результаты подтверждают, что наивные плюрипотентные клетки более эффективно участвуют в формировании химер и что клеточная элиминация происходит, если клетки находятся на разных стадиях развития [@toyooka_identification_2008].

MYC выступает консервативным маркером клеточной конкуренции, при этом клетки с низким уровнем MYC чаще оказываются «проигравшими» [@cova_drosophila_2004; @moreno_dmyc_2004; @claveria_myc-driven_2013]. Интересно, что клетки, культивируемые в среде 2i с LIF, демонстрируют более низкий уровень экспрессии MYC по сравнению с клетками в сывороточной среде с LIF. В последнем случае разница в уровне MYC между более и менее дифференцированными клетками не наблюдается. Это позволяет предположить, что в данном контексте конкуренция может не инициироваться за счет различий в экспрессии MYC.

Дополнительные доказательства того, что различия в состоянии клеток вызывают их элиминацию, получены в экспериментах с эпибластными стволовыми клетками (эпиСК). Эти клетки находятся в состоянии плюрипотентности, характерном для стадии постимплантационного развития эмбриона, и не могут формировать химеры при введении в эмбрионы на предимплантационной стадии развития [@nichols_suppression_2009; @brons_derivation_2007; @tesar_new_2007]. Ранее предполагалось, что неспособность эпиСК интегрироваться в эмбрион происходит из-за несоответствия стадии развития. Однако при индуцированной экспрессии антиапоптотического фактора BCL2 такие клетки успешно формировали химеры [@masaki_inhibition_2016]. Это указывает на то, что они не испытывают проблем с интеграцией в эмбрион, но вместо этого уничтожаются в окружении клеток, находящихся на другой стадии развития.

Убедительные доказательства роли клеточной конкуренции были получены при анализе поведения клеток с различным уровнем экспрессии MYC. Визуализация живых ЭСК с GFP-MYC показала, что клетки с высоким уровнем экспрессии MYC устраняют клетки с низким уровнем экспрессии MYC, поскольку последние находятся в состоянии, близком к состоянию дифференцировки [@diaz-diaz_pluripotency_2017].

В совокупности приведенные выше результаты позволяют предположить, что клеточная конкуренция играет важную роль в раннем эмбриональном развитии млекопитающих, обеспечивая координированное развитие клеток в ткани и способствуя гомогенности процессов дифференцировки.

### **1.5.2. Элиминация клеток с кариотипическими аномалиями**

Кариотипические аномалии могут быть летальными на поздних стадиях эмбрионального развития человека. Однако, как и в эмбриогенезе мыши, анеуплоидия часто встречается на ранних стадиях развития человеческого эмбриона: 50–80% эмбрионов демонстрируют мозаичную анеуплоидию на предимплантационной стадии [@van_echten-arends_chromosomal_2011]. На более поздних сроках беременности уровень анеуплоидии значительно снижается, что свидетельствует об устранении анеуплоидных клеток в процессе развития [@kalousek_confirmation_1991].

Данные, полученные на мышиных эмбрионах и человеческих плюрипотентных стволовых клетках (чПСК), указывают на то, что этот отбор происходит на ранних этапах дифференцировки [@horii_p53_2015; @sancho_competitive_2013; @singla_autophagy-mediated_2020]. Например, в химерах, сформированных из тетраплоидных клеток и клеток дикого типа, тетраплоидные клетки устраняются путём апоптоза в ранний постимплантационный период [@sancho_competitive_2013]. Этот процесс зависит от активности белка p53 и подавления сигнального пути mTOR, поскольку мутации в генах p53 или Tsc2 (репрессор mTOR) предотвращают элиминацию тетраплоидных клеток [@horii_p53_2015; @bowling_p53_2018].

Наблюдение за тетраплоидными ЭСК показало, что их элиминация происходит через клеточную конкуренцию, поскольку апоптоз специфически индуцируется только в присутствии клеток дикого типа [@sancho_competitive_2013; @bowling_p53_2018]. Аналогичные наблюдения были сделаны в химерах, сформированных из эуплоидных и анеуплоидных клеток, полученных после обработки реверсином, который вызывает анеуплоидию путём ингибирования контрольной точки сборки веретена деления. В этих химерах анеуплоидные клетки эмбриональной ткани устраняются апоптозом, который происходит в предимплантационный и ранний постимплантационный периоды, зависит от p53 и аутoфагии — механизма, который действует ниже по сигнальному пути mTOR [@singla_autophagy-mediated_2020]. В отличие от этого, в будущих плацентарных тканях анеуплоидия приводит к замедленному пролиферативному росту, но не к клеточной гибели. Это говорит о том, что апоптоз анеуплоидных клеток носит клеточный, внутренний характер и не всегда индуцируется нормальными клетками. Однако обработка реверсином не приводит к образованию однородной популяции анеуплоидных клеток, и возможно, некоторые клетки не подвергаются воздействию реверсина или подвергаются лишь минимальному воздействию, и именно они конкурируют с уничтоженными клетками.

Тем не менее, при добавлении 25% эуплоидных клеток, анеуплоидные клетки оказывались преимущественно в экстраэмбриональных линиях, при этом уровень анеуплоидии снижался с 82% в эмбрионах E3 до 5% к стадии E7, что дополнительно подтверждает гипотезу об устранении анеуплоидных клеток в ходе развития [@yang_depletion_2021]. Анализ транскриптома анеуплоидных клеток, обнаруженных в человеческих эмбрионах на этих стадиях развития, продемонстрировал наличие генетических сигнатур, ассоциированных с активностью онкогена MYC и сигнальным каскадом mTOR, что соответствует признакам клеточной конкуренции, ранее идентифицированными в экспериментах на мышиных эмбрионах [@claveria_myc-driven_2013; @sancho_competitive_2013; @bowling_p53_2018; @starostik_single-cell_2020].

Полученные данные позволяют предположить, что элиминация клеток с кариотипическими нарушениями через механизм клеточной конкуренции выступает эффективным адаптивным механизмом контроля качества, предотвращающим распространение генетических ошибок на ранних этапах эмбрионального развития. Убедительным подтверждением служат клинические наблюдения успешных случаев беременности после переноса эмбрионов с мозаичной анеуплоидией, которые завершились рождением здоровых детей [@van_echten-arends_chromosomal_2011; @vanneste_chromosome_2009].

Несмотря на негативные последствия анеуплоидии, 12,5–34% человеческих плюрипотентных клеточных линий со временем приобретают хромосомные аномалии [@na_aneuploidy_2014]. Это указывает на то, что некоторые виды анеуплоидии дают плюрипотентным клеткам селективное преимущество. Например, показано, что чЭСК с приобретённой анеуплоидией индуцируют механическое давление на нормальные клетки, активируя сигнальный путь Hippo и вызывая элиминацию этих клеток через клеточную конкуренцию [@price_genetically_2021]. Это позволяет предположить, что тип анеуплоидии определяет исход клеточной конкуренции: один тип делает клетки «проигравшими», тогда как другие типы — «победителями». Требуются дальнейшие научные исследования для установления механизмов, посредством которых разные типы хромосомных аномалий вызывают различное конкурентное поведение клеток.

### **1.5.3. Элиминация клеток с митохондриальной дисфункцией**

После имплантации клетки эмбриона мыши вступают в фазу быстрого пролиферативного деления, при этом средняя продолжительность клеточного цикла уменьшается с \~11,5 часов для клеток эпибласта на стадии E5.5 до \~4,4 часов для клеток эмбриона на стадии гаструляции E7 [@snow_gastrulation_1977]. Одновременно с ускорением пролиферации клетки эпибласта начинают выходить из состояния плюрипотентности и приобретать специализацию в направлениях мезодермы, энтодермы или эктодермы. Этот процесс сопровождается масштабной перестройкой эпигенетического, метаболического и сигнального ландшафта клеток. Такие значительные изменения создают высокий риск возникновения аномальных клеток, которые должны быть устранены, чтобы предотвратить их влияние на развитие эмбриона.

В рамках исследования процессов клеточной селекции в эмбриональном развитии млекопитающих было установлено, что на стадии гаструляции происходит значимая волна клеточной элиминации [@manova_apoptosis_1998; @spruce_early_2010]. У эмбрионов мыши на стадии E6.5 примерно 35% клеток эпибласта подвергаются устранению в течение 18-часового временного интервала [@bowling_p53_2018]. Первые научные свидетельства того, что элиминация, скорее всего, происходит в результате конкуренции, были получены при изучении элиминированных клеток с пониженным уровнем белка c-MYC, что является характерным признаком клеточной конкуренции. Экспериментально доказано, что при избыточной экспрессии MYC в E6.5 в части клеток эпибласта происходит апоптотическая элиминация клеток с низкой концентрацией этого белка [@claveria_myc-driven_2013; @sancho_competitive_2013]. Аналогичным образом, при совместном культивировании жизнеспособных, но дефектных ЭСК с нормальными клетками, дефектные клетки также устранялись посредством клеточной конкуренции [@sancho_competitive_2013]. Эти данные позволяют предположить, что в раннем постимплантационном эмбрионе клеточная конкуренция выполняет функцию контроля качества, устраняя менее пригодные клетки с низким уровнем MYC.

Первые данные о том, что эта элиминация может происходить посредством клеточной конкуренции, пришли из наблюдений за клетками-«проигравшими», окруженными клетками-«победителями». Было обнаружено, что как in vitro, так и in vivo дефектные клетки демонстрируют повышенную экспрессию р53. В присутствии клеток дикого типа активность p53 изменяется таким образом, что он подавляет путь mTOR, инициируя элиминацию дефектных клеток. Мутации в генах p53 или Tsc2 (репрессор mTOR) не только предотвращают элиминацию дефектных клеток, но и превращают такие клетки в «суперконкурентов», которые способны устранять соседние нормальные клетки [@bowling_p53_2018]. Эти результаты показывают, что сигнальные пути MYC, P53 и mTOR играют ключевую роль в клеточной конкуренции в эпибласте после имплантации.

Исследователи провели транскриптомный анализ одиночных клеток эмбрионов на стадии E6.5, заблокировав апоптоз на 18 часов, что позволило исследовать клетки, обычно подлежащие элиминации. Сравнение транскриптомного профиля таких клеток с нормальными показало, низкий уровень экспрессии MYC и mTOR, но высокий уровень экспрессии p53, что свидетельствует о том, что в нормальных условиях такие клетки устранялись бы через клеточную конкуренцию. Дополнительный анализ выявил у клеток, предрасположенных к элиминации, митохондриальную дисфункцию и накопление мутаций в митохондриальной ДНК (мтДНК) [@lima_cell_2021]. Важно, что нарушение митохондриальной динамики или введение небольшого количества непатогенных изменений в мтДНК способны кардинально изменить статус клеток, переводя их в категорию «проигравших». Эти результаты позволяют нам предположить, что в период раннего постимплантационного развития клеточная конкуренция выступает механизмом селекции клеток эпибласта за счет элиминации клеток, имеющих более низкую митохондриальную активность, чем их соседи. Исследования демонстрируют, что митохондриальная дисфункция является общим маркером клеток с различными патологическими изменениями, включая метаболические нарушения, сбои в сигнальных системах и хромосомные аберрации [@lima_cell_2021]. Это позволяет предположить, что подобная дисфункция может рассматриваться как универсальный признак клеток с низким потенциалом жизнеспособности, который идентифицируется в ходе межклеточной конкуренции.

Митохондрии играют ключевую роль в координации клеточных ответов на протеостатический и метаболический стресс [@andreasson_mitochondria_2019]. В рамках биохимической клеточной конкуренции ученые выдвигают гипотезу о том, что конкурентоспособность клетки определяется ее способностью реагировать на митохондриальный и протеотоксический стресс. Предполагается, что две клетки с существенными различиями в митохондриальной активности или протеостазе обладают принципиально разными секретомами, к которым они генетически адаптированы. При непосредственном контакте этих клеточных популяций происходит взаимодействие их секретомов, формирующее новую микросреду, которая создает серьезный вызов протеостазу и митохондриальному гомеостазу каждого клеточного типа. Существуют научные данные о неавтономной регуляции протеостаза и механизмов митохондриального стресса, и такая регуляция с высокой вероятностью подвергается влиянию изменений в микроокружении. В предложенной теоретической модели клетки, способные наиболее эффективно адаптироваться и выживать в условиях протеотоксического или митохондриального стресса, становятся «победителями» в клеточной конкуренции. Примечательно, что некоторые из генов, играющих ключевую роль в клеточной конкуренции, включая Myc, mTOR и p53, являются известными регуляторами митохондриальной активности и протеостаза [@kim_mtor_2019; @kruiswijk_p53_2015; @zhang_myc_2020]. Это повышает вероятность того, что они могут влиять на исход клеточной конкуренции посредством регуляции указанных процессов.
